language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
services:
  - mongodb
env: 
  - LAIKA_OPTIONS="-t 5000"

deploy:
  provider: opsworks
  access_key_id: AKIAIEFSC7JATHBJKBQA
  secret_access_key:
    secure: AluXtXCK8V/DAKwwbQJBxE0krb0hE0e47yH2vL7QVsUmZ8PDwo+SlXltvP6wMfOlrohLHRisxNl4fubfti42IjmkjKhH5F2SAz6s4TrkgXhnE4BcCnN8znYbA0/WorE9zHHYSw4dOTyvUXVz2ENcMNnaTQUSm7qWAnOtp444vGE=
  app-id: ca522848-9587-4c73-8699-5d5d72675a95
  on:
    repo: skyveri/skyveri-main-site
